site_name: https://github.com/FrankLef/flp_todo.git (Repo name)

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md
